//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaLamViec
    {
        public string maCaTruc { get; set; }
        public Nullable<System.DateTime> ngayLamViec { get; set; }
        public Nullable<System.TimeSpan> gioMoCa { get; set; }
        public Nullable<System.TimeSpan> gioDongCa { get; set; }
    
        public virtual CT_CaLamViec CT_CaLamViec { get; set; }
    }
}
