//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMucSach
    {
        public string maSP { get; set; }
        public string tenSP { get; set; }
        public string nhaXuatBan { get; set; }
        public Nullable<System.DateTime> ngayXuatBan { get; set; }
        public Nullable<int> soLuongTon { get; set; }
        public string tacGia { get; set; }

        public virtual SanPham SanPham { get; set; }
    }
}
