//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.CT_HD = new HashSet<CT_HD>();
        }
    
        public string maSP { get; set; }
        public string tenSP { get; set; }
        public string hangMuc { get; set; }
        public int donGia { get; set; }
        public string donVi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HD> CT_HD { get; set; }
        public virtual DanhMucSach DanhMucSach { get; set; }
        public virtual DanhMucVanPhongPham DanhMucVanPhongPham { get; set; }
    }
}
